# Generated by Django 5.0.6 on 2024-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level5_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='pot_url',
            field=models.URLField(blank=True),
        ),
    ]
